### ISSUE TITLE
[Questions] - General Questions

### ISSUE THREAD

**Issue by go4cas** [ais-one/vue-crud-x#53]
@ais-one ... keen to try out this template. I do have a few questions:

- Can one use custom components in the `crudTable`?
- Is auth included, or would I need to implement my own auth workflow?
- Can values for `v-select` (inside `crudTable` and `crudFilter`) be loaded from API or vuex?

**Comment by ais-one** [comment]
Hi,

1st Point

Are you mentioning about custom input components?

If it is for inline edit, possible, but it is limited (look at line 668 to 709 of the file), you need to see if you need to handle events, if v-model only it should be ok

If it is on the crudForm, basically, if you use the new way of using <slots> your add and edit UI can be heavily customized and you can add your custom components


2nd Point

For the auth part there are 3 examples
1. using firebase authentication
2. the  nuxt example has an example of social login (you can use most other oauth2 logins instead of github)
3. there is JWT authentication also in both Nuxt and Vanilla VueJS example connecting to the REST API.

auth is not just about frontend, but it also needs backend.


3rd Point

if you want to have typeahead and pulling from API, It is probably better to use v-autocomplete and with RxJS (it makes code cleaner), there is any example somewhere in the code.

**Comment by ais-one** [comment]
1. as of version 0.2, you can use some slots for custom components in the crud Table...
2 we realize that auth need not be included, and it happens mostly on server side
3. yes, please see an example with v-autocomplete
